name: echoquest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  string_similarity: ^2.0.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  shared_preferences: ^2.5.2
  audioplayers: ^6.3.0
  http: ^1.3.0
  flutter_markdown: ^0.6.10
  flutter_svg: ^1.1.0
  flutter_bluetooth_serial: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/img/logo.jpg
    - lib/img/background.jpg
    - lib/img/level back.jpg
    - lib/img/all back.jpg
    - assets/sounds/mic_on.mp3
